#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define BOOT_BUTTON_GPIO GPIO_NUM_28

#define ML307_TX_GPIO GPIO_NUM_11
#define ML307_RX_GPIO GPIO_NUM_12

#define CODEC_TX_GPIO GPIO_NUM_7
#define CODEC_RX_GPIO GPIO_NUM_8

#define BATTERY_CHANG_GPIO GPIO_NUM_15
#define BATTERY_ADC_GPIO GPIO_NUM_5

#define RBG_DI_GPIO GPIO_NUM_6

#define POWER_KRRP_GPIO GPIO_NUM_27

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_9
#define DISPLAY_MOSI_PIN GPIO_NUM_0
#define DISPLAY_CLK_PIN GPIO_NUM_1
#define DISPLAY_DC_PIN GPIO_NUM_2
#define DISPLAY_RST_PIN GPIO_NUM_3
#define DISPLAY_CS_PIN GPIO_NUM_4
#define DISPLAY_TE_PIN GPIO_NUM_10

#define DISPLAY_INVERT_COLOR true
#define DISPLAY_SWAP_XY true
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_WIDTH 296
#define DISPLAY_HEIGHT 240
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#endif // _BOARD_CONFIG_H_
